---
site:
  title: OpenShift Virtualization GitOps Workshop
  url: https://github.com/rhpds/ocp-virt-gitops-showroom
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/latest/ui-bundle.zip
    snapshot: true

antora:
  extensions:
    - '@sntke/antora-mermaid-extension'

output:
  dir: ./www
