---
type: showroom

# Set the left column width to 40% for longer lab instructions
default_width: 40
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

view_switcher:
  enabled: false
  default_mode: instructions

tabs:
  # Single terminal
  - name: Terminal
    path: /wetty
    port: 443

  # OCP Console
  - name: OCP Console
    url: 'https://console-openshift-console.${DOMAIN}'
